"""baseline schema — relational realisation of schemas/ (docs/04 §3)

Creates the governance tables (patient_profile, consent, audit_log,
version_registry), the per-reading table, the versioned PSG node tables, and the
persisted-output table. Forward-only and backward-compatible per docs/09; this is
the T0.2 baseline that later migrations extend.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-29
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergy_node",
        sa.Column("substance_code", sa.String(), nullable=False),
        sa.Column("reaction", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allergy_node_patient_id"), "allergy_node", ["patient_id"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("input_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint("hash"),
        sa.UniqueConstraint("seq"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_patient_id"), "audit_log", ["patient_id"], unique=False)
    op.create_index(op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False)
    op.create_table(
        "baseline_node",
        sa.Column("metric_code", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("center", sa.Float(), nullable=False),
        sa.Column("dispersion", sa.Float(), nullable=False),
        sa.Column("sample_n", sa.Integer(), nullable=False),
        sa.Column("window_spec", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_population_fallback", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_baseline_node_patient_id"), "baseline_node", ["patient_id"], unique=False
    )
    op.create_table(
        "condition_node",
        sa.Column("snomed_code", sa.String(), nullable=False),
        sa.Column("display", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("onset", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_condition_node_patient_id"), "condition_node", ["patient_id"], unique=False
    )
    op.create_table(
        "deviation_node",
        sa.Column("metric_code", sa.String(), nullable=False),
        sa.Column("baseline_id", sa.Uuid(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("z_robust", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_population_fallback", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deviation_node_patient_id"), "deviation_node", ["patient_id"], unique=False
    )
    op.create_table(
        "event_node",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("onset_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contributing_deviation_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_node_patient_id"), "event_node", ["patient_id"], unique=False)
    op.create_table(
        "forecast_node",
        sa.Column("metric_code", sa.String(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intervals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forecast_node_patient_id"), "forecast_node", ["patient_id"], unique=False
    )
    op.create_table(
        "medication_node",
        sa.Column("rxnorm_code", sa.String(), nullable=False),
        sa.Column("display", sa.String(), nullable=False),
        sa.Column("dose", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_node_patient_id"), "medication_node", ["patient_id"], unique=False
    )
    op.create_table(
        "observation_node",
        sa.Column("loinc_code", sa.String(), nullable=False),
        sa.Column("display", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observation_node_patient_id"), "observation_node", ["patient_id"], unique=False
    )
    op.create_table(
        "output",
        sa.Column("output_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("baseline_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommended_action", sa.String(), nullable=False),
        sa.Column("escalation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abstained", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("output_id"),
    )
    op.create_index(op.f("ix_output_patient_id"), "output", ["patient_id"], unique=False)
    op.create_table(
        "patient_profile",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("sex_at_birth", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("age_years", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("weight_measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blood_group", sa.String(), nullable=True),
        sa.Column("physical_disability", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("patient_id"),
    )
    op.create_table(
        "reading_node",
        sa.Column("reading_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("metric_code", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("ts_tz", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_device", sa.String(), nullable=False),
        sa.Column("sqi", sa.Float(), nullable=False),
        sa.Column("context", sa.String(), nullable=False),
        sa.Column("included_in_baseline", sa.Boolean(), nullable=False),
        sa.Column("ingest_adapter", sa.String(), nullable=False),
        sa.Column("raw_ref", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("reading_id"),
    )
    op.create_index(
        op.f("ix_reading_node_patient_id"), "reading_node", ["patient_id"], unique=False
    )
    op.create_table(
        "version_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_version_registry_active_kind",
        "version_registry",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "consent",
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("scope", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profile.patient_id"],
        ),
        sa.PrimaryKeyConstraint("consent_id"),
    )
    op.create_index(op.f("ix_consent_patient_id"), "consent", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consent_patient_id"), table_name="consent")
    op.drop_table("consent")
    op.drop_index(
        "uq_version_registry_active_kind",
        table_name="version_registry",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("version_registry")
    op.drop_index(op.f("ix_reading_node_patient_id"), table_name="reading_node")
    op.drop_table("reading_node")
    op.drop_table("patient_profile")
    op.drop_index(op.f("ix_output_patient_id"), table_name="output")
    op.drop_table("output")
    op.drop_index(op.f("ix_observation_node_patient_id"), table_name="observation_node")
    op.drop_table("observation_node")
    op.drop_index(op.f("ix_medication_node_patient_id"), table_name="medication_node")
    op.drop_table("medication_node")
    op.drop_index(op.f("ix_forecast_node_patient_id"), table_name="forecast_node")
    op.drop_table("forecast_node")
    op.drop_index(op.f("ix_event_node_patient_id"), table_name="event_node")
    op.drop_table("event_node")
    op.drop_index(op.f("ix_deviation_node_patient_id"), table_name="deviation_node")
    op.drop_table("deviation_node")
    op.drop_index(op.f("ix_condition_node_patient_id"), table_name="condition_node")
    op.drop_table("condition_node")
    op.drop_index(op.f("ix_baseline_node_patient_id"), table_name="baseline_node")
    op.drop_table("baseline_node")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_patient_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_allergy_node_patient_id"), table_name="allergy_node")
    op.drop_table("allergy_node")
    # ### end Alembic commands ###
